### ISSUE TITLE
【HELP】in file src/main.cc the api  ps::Start(); is lost param?

### ISSUE THREAD

**Issue by xjj210130** [xswang/Field-aware-Factorization-Machine-ps#6]
hi all:
    I don't know the API come from.
    ps::Start(); in file src/main.cc
 meanwhile, i find the ps-lite api is following:
inline void Start(int customer_id, const char* argv0 = nullptr) {
  Postoffice::Get()->Start(customer_id, argv0, true);
}

**Comment by xswang** [comment]
hi，xjj210130,
ps::Start will call the function: inline void Start(const char* argv0 = nullptr) ,  this function is in file of ps-lite/include/ps/ps.h,  the parameter argv0 is a default parameter,  it`s value is default to be nullptr, so it will work.
