### ISSUE TITLE
Check failed: (my_node_.port) != (-1) bind failed

### ISSUE THREAD

**Issue by microdyb** [xswang/Field-aware-Factorization-Machine-ps#7]
When I tried to run the following command:
bash run_ps_local.sh 2 100

It got something wrong like this:

[16:54:41] /home/duyb/APSGD/xflow/ps-lite/include/dmlc/logging.h:208: [16:54:41] /home/duyb/APSGD/xflow/ps-lite/src/van.cc:76: Check failed: (my_node_.port) != (-1) bind failed
terminate called after throwing an instance of 'dmlc::Error'
  what():  [16:54:41] /home/duyb/APSGD/xflow/ps-lite/src/van.cc:76: Check failed: (my_node_.port) != (-1) bind failed

How could I fix it?

**Comment by peterzhang2029** [comment]
You should make sure the port is available(default 8000).
